# Generated by Django 4.2.3 on 2024-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='img',
            field=models.ImageField(upload_to='media/shoe/'),
        ),
    ]
